### ISSUE TITLE
4.36式について

### ISSUE THREAD

**Issue by deasuke** [sammy-suyama/BayesianDeepLearningBook#2]
この式の変形でP(Z,W)=P(Z)P(W)を使っていると思われますが、ZとWが独立なのは仮定でしょうか？
一般にinput parametersとlatent variablesは独立と仮定するのでしょうか？教えて頂けると幸いです。

**Comment by sammy-suyama** [comment]
式4.33および式4.34において事前分ではWとZが独立であることを仮定しています。
